<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ClipHat</AssemblyName>
    <Version>1.3.0</Version>
    <ApplicationIcon>assets\ClipHat.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets/ClipHat.png" LogicalName="ClipHat.AppIcon.png" />
  </ItemGroup>
</Project>
